/**
 * ============================================================
 * groqTestRunner.js - Execute AI-Generated Playwright Tests
 * ============================================================
 * Takes Playwright test code generated by Groq AI, saves it,
 * executes it, and returns structured results.
 * ============================================================
 */

const { chromium } = require('playwright');
const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');

const TESTS_DIR = path.join(__dirname, 'groq_tests');
const RESULTS_DIR = path.join(__dirname, 'groq_results');

// Ensure directories exist
[TESTS_DIR, RESULTS_DIR].forEach(dir => {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
});

/**
 * Execute AI-generated test code against a target URL
 * Instead of using @playwright/test runner, we parse and run tests directly
 * for real-time results streaming.
 *
 * @param {string} testCode - The generated Playwright test code
 * @param {string} pageUrl - The target URL
 * @param {string} testFileName - Name for the test file
 * @param {function} sendUpdate - Callback for live updates
 * @returns {object} Execution results
 */
async function executeGroqTests(testCode, pageUrl, testFileName, sendUpdate) {
    const runId = uuidv4().substring(0, 8);
    const results = {
        runId,
        testFileName,
        pageUrl,
        startTime: new Date().toISOString(),
        endTime: null,
        totalTests: 0,
        passed: 0,
        failed: 0,
        skipped: 0,
        testResults: [],
        savedTestFile: '',
        status: 'running',
        error: null,
    };

    // Save the test code to a file for reference
    const safeFileName = testFileName.replace(/[^a-zA-Z0-9_.-]/g, '_');
    const testFilePath = path.join(TESTS_DIR, `${runId}_${safeFileName}`);
    fs.writeFileSync(testFilePath, testCode, 'utf-8');
    results.savedTestFile = testFilePath;

    if (sendUpdate) {
        sendUpdate({
            type: 'groq-test-execution-start',
            runId,
            message: `🧪 Starting test execution for: ${pageUrl}`,
            totalTests: 0,
        });
    }

    let browser = null;

    try {
        // Parse test descriptions from code
        const testDescriptions = extractTestDescriptions(testCode);
        results.totalTests = testDescriptions.length;

        if (sendUpdate) {
            sendUpdate({
                type: 'groq-test-count',
                runId,
                totalTests: testDescriptions.length,
                tests: testDescriptions,
                message: `📋 Found ${testDescriptions.length} test cases to execute`,
            });
        }

        // Launch browser for test execution
        browser = await chromium.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox'],
        });

        const context = await browser.newContext({
            viewport: { width: 1920, height: 1080 },
            ignoreHTTPSErrors: true,
        });

        const page = await context.newPage();

        // Navigate to the target URL
        await page.goto(pageUrl, { waitUntil: 'load', timeout: 30000 }).catch(() => {
            return page.goto(pageUrl, { waitUntil: 'domcontentloaded', timeout: 20000 });
        });
        await page.waitForTimeout(2000);

        // Run each test description as an individual check
        for (let i = 0; i < testDescriptions.length; i++) {
            const testDesc = testDescriptions[i];
            const testResult = {
                index: i,
                name: testDesc.name,
                type: testDesc.type || 'functional',
                status: 'running',
                duration: 0,
                error: null,
                details: '',
            };

            if (sendUpdate) {
                sendUpdate({
                    type: 'groq-test-running',
                    runId,
                    testIndex: i,
                    testName: testDesc.name,
                    message: `▶️ Running: ${testDesc.name}`,
                });
            }

            const testStart = Date.now();

            try {
                // Execute the test based on its type
                const outcome = await runSingleTest(page, context, testDesc, pageUrl);
                testResult.status = outcome.passed ? 'passed' : 'failed';
                testResult.details = outcome.details;
                testResult.error = outcome.error || null;

                if (outcome.passed) {
                    results.passed++;
                } else {
                    results.failed++;
                }
            } catch (err) {
                testResult.status = 'failed';
                testResult.error = err.message;
                testResult.details = `Exception: ${err.message}`;
                results.failed++;
            }

            testResult.duration = Date.now() - testStart;
            results.testResults.push(testResult);

            if (sendUpdate) {
                sendUpdate({
                    type: 'groq-test-result',
                    runId,
                    testIndex: i,
                    testName: testDesc.name,
                    status: testResult.status,
                    duration: testResult.duration,
                    error: testResult.error,
                    details: testResult.details,
                    message: `${testResult.status === 'passed' ? '✅' : '❌'} ${testDesc.name}: ${testResult.status.toUpperCase()} (${testResult.duration}ms)`,
                });
            }

            // Re-navigate to original page if URL changed
            const currentUrl = page.url();
            if (currentUrl !== pageUrl && !currentUrl.startsWith(new URL(pageUrl).origin)) {
                await page.goto(pageUrl, { waitUntil: 'load', timeout: 15000 }).catch(() => {});
                await page.waitForTimeout(1000);
            }
        }

        results.status = 'complete';
    } catch (error) {
        results.status = 'error';
        results.error = error.message;
    } finally {
        if (browser) {
            await browser.close();
        }
    }

    results.endTime = new Date().toISOString();

    // Save results
    const resultsPath = path.join(RESULTS_DIR, `${runId}_results.json`);
    fs.writeFileSync(resultsPath, JSON.stringify(results, null, 2));

    if (sendUpdate) {
        sendUpdate({
            type: 'groq-test-execution-complete',
            runId,
            results: {
                totalTests: results.totalTests,
                passed: results.passed,
                failed: results.failed,
                skipped: results.skipped,
                testResults: results.testResults,
                status: results.status,
            },
            message: `🏁 Tests complete: ${results.passed} passed, ${results.failed} failed out of ${results.totalTests}`,
        });
    }

    return results;
}

/**
 * Extract test descriptions from generated Playwright code
 */
function extractTestDescriptions(testCode) {
    const tests = [];

    // Match test('name', ...) or test("name", ...) patterns
    const testPattern = /test\s*\(\s*['"`]([^'"`]+)['"`]/g;
    let match;
    let idx = 0;

    while ((match = testPattern.exec(testCode)) !== null) {
        const name = match[1];

        // Determine type from test name
        let type = 'functional';
        const nameLower = name.toLowerCase();
        if (nameLower.includes('nav') || nameLower.includes('link') || nameLower.includes('menu')) type = 'navigation';
        else if (nameLower.includes('form') || nameLower.includes('input') || nameLower.includes('submit')) type = 'form';
        else if (nameLower.includes('button') || nameLower.includes('click')) type = 'button';
        else if (nameLower.includes('visual') || nameLower.includes('layout') || nameLower.includes('display')) type = 'visual';
        else if (nameLower.includes('error') || nameLower.includes('invalid') || nameLower.includes('negative')) type = 'error';
        else if (nameLower.includes('seo') || nameLower.includes('meta') || nameLower.includes('title')) type = 'seo';
        else if (nameLower.includes('responsive') || nameLower.includes('mobile')) type = 'responsive';
        else if (nameLower.includes('image') || nameLower.includes('logo')) type = 'visual';
        else if (nameLower.includes('header') || nameLower.includes('footer')) type = 'navigation';

        tests.push({ index: idx, name, type });
        idx++;
    }

    // If no tests found via regex, create generic tests from testList
    if (tests.length === 0) {
        tests.push(
            { index: 0, name: 'Page loads successfully', type: 'functional' },
            { index: 1, name: 'Page title is present', type: 'seo' },
            { index: 2, name: 'Navigation elements visible', type: 'navigation' },
            { index: 3, name: 'No console errors', type: 'error' },
            { index: 4, name: 'All images load correctly', type: 'visual' },
        );
    }

    return tests;
}

/**
 * Execute a single test against the page
 */
async function runSingleTest(page, context, testDesc, pageUrl) {
    const nameLower = testDesc.name.toLowerCase();

    // ═══════════════════════════════════════════
    // PAGE LOAD TESTS
    // ═══════════════════════════════════════════
    if (nameLower.includes('load') || nameLower.includes('opens') || nameLower.includes('accessible')) {
        const response = await page.goto(pageUrl, { waitUntil: 'domcontentloaded', timeout: 20000 }).catch(e => null);
        if (response && response.ok()) {
            return { passed: true, details: `Page loaded with status ${response.status()}` };
        }
        return { passed: false, details: `Page load failed`, error: response ? `Status: ${response.status()}` : 'No response' };
    }

    // ═══════════════════════════════════════════
    // TITLE / SEO TESTS
    // ═══════════════════════════════════════════
    if (nameLower.includes('title')) {
        const title = await page.title();
        if (title && title.length > 0 && title !== 'about:blank') {
            return { passed: true, details: `Title found: "${title}"` };
        }
        return { passed: false, details: 'Page title is empty or missing', error: 'No title' };
    }

    if (nameLower.includes('meta') || nameLower.includes('seo')) {
        const metaDesc = await page.$eval('meta[name="description"]', el => el.content).catch(() => null);
        const hasViewport = await page.$('meta[name="viewport"]') !== null;
        const h1Count = await page.$$eval('h1', els => els.length);

        const issues = [];
        if (!metaDesc) issues.push('Missing meta description');
        if (!hasViewport) issues.push('Missing viewport meta');
        if (h1Count === 0) issues.push('No H1 tag');
        if (h1Count > 1) issues.push(`Multiple H1 tags (${h1Count})`);

        if (issues.length === 0) {
            return { passed: true, details: 'All SEO meta tags present' };
        }
        return { passed: false, details: issues.join(', '), error: issues.join('; ') };
    }

    // ═══════════════════════════════════════════
    // NAVIGATION TESTS
    // ═══════════════════════════════════════════
    if (nameLower.includes('header') || nameLower.includes('navigation') || nameLower.includes('nav')) {
        const hasHeader = await page.$('header, nav, [role="navigation"], .navbar, .header') !== null;
        const navLinks = await page.$$eval(
            'header a, nav a, [role="navigation"] a',
            els => els.filter(el => el.offsetParent !== null).length
        ).catch(() => 0);

        if (hasHeader && navLinks > 0) {
            return { passed: true, details: `Navigation found with ${navLinks} links` };
        }
        return { passed: hasHeader, details: hasHeader ? `Header found but only ${navLinks} nav links` : 'No header/nav element found', error: !hasHeader ? 'Missing header' : null };
    }

    if (nameLower.includes('footer')) {
        const hasFooter = await page.$('footer, .footer, #footer') !== null;
        if (hasFooter) {
            return { passed: true, details: 'Footer element found' };
        }
        return { passed: false, details: 'No footer element found', error: 'Missing footer' };
    }

    if (nameLower.includes('link') && !nameLower.includes('broken')) {
        const links = await page.$$eval('a[href]', els =>
            els.filter(el => el.offsetParent !== null).slice(0, 5).map(el => ({
                text: el.textContent.trim().substring(0, 30),
                href: el.href,
            }))
        ).catch(() => []);

        if (links.length > 0) {
            return { passed: true, details: `Found ${links.length} visible links` };
        }
        return { passed: false, details: 'No visible links found', error: 'No links' };
    }

    // ═══════════════════════════════════════════
    // BUTTON TESTS
    // ═══════════════════════════════════════════
    if (nameLower.includes('button') || nameLower.includes('click') || nameLower.includes('cta')) {
        const buttons = await page.$$eval(
            'button, input[type="submit"], input[type="button"], a.btn, [role="button"]',
            els => els.filter(el => {
                const style = window.getComputedStyle(el);
                return style.display !== 'none' && style.visibility !== 'hidden' && el.offsetParent !== null;
            }).map(el => ({
                text: (el.textContent || el.value || el.getAttribute('aria-label') || '').trim().substring(0, 40),
                tag: el.tagName,
                disabled: el.disabled || false,
            }))
        ).catch(() => []);

        if (buttons.length > 0) {
            const enabledButtons = buttons.filter(b => !b.disabled);
            return {
                passed: true,
                details: `Found ${buttons.length} buttons (${enabledButtons.length} enabled): ${buttons.slice(0, 3).map(b => b.text || 'unnamed').join(', ')}`,
            };
        }
        return { passed: false, details: 'No interactive buttons found', error: 'No buttons' };
    }

    // ═══════════════════════════════════════════
    // FORM / INPUT TESTS
    // ═══════════════════════════════════════════
    if (nameLower.includes('form') || nameLower.includes('input') || nameLower.includes('field')) {
        const forms = await page.$$eval('form', els => els.length).catch(() => 0);
        const inputs = await page.$$eval(
            'input:not([type="hidden"]), textarea, select',
            els => els.filter(el => el.offsetParent !== null).map(el => ({
                type: el.type || el.tagName.toLowerCase(),
                name: el.name || el.id || '',
                placeholder: el.placeholder || '',
            }))
        ).catch(() => []);

        if (inputs.length > 0 || forms > 0) {
            return {
                passed: true,
                details: `Found ${forms} form(s), ${inputs.length} input field(s)`,
            };
        }
        return {
            passed: nameLower.includes('no ') || nameLower.includes('empty'),
            details: 'No forms or input fields found',
            error: 'No inputs',
        };
    }

    if (nameLower.includes('submit') || nameLower.includes('validation')) {
        const submitBtns = await page.$$eval(
            'button[type="submit"], input[type="submit"], button:not([type])',
            els => els.filter(el => el.offsetParent !== null).length
        ).catch(() => 0);

        if (submitBtns > 0) {
            return { passed: true, details: `Found ${submitBtns} submit button(s)` };
        }
        return { passed: false, details: 'No submit buttons found', error: 'No submit' };
    }

    // ═══════════════════════════════════════════
    // IMAGE TESTS
    // ═══════════════════════════════════════════
    if (nameLower.includes('image') || nameLower.includes('logo') || nameLower.includes('img')) {
        const imageStats = await page.evaluate(() => {
            const imgs = Array.from(document.querySelectorAll('img'));
            const broken = imgs.filter(img => img.complete && img.naturalWidth === 0 && img.src && img.src !== '#');
            const missingAlt = imgs.filter(img => !img.alt || img.alt.trim() === '');
            return {
                total: imgs.length,
                broken: broken.length,
                missingAlt: missingAlt.length,
            };
        }).catch(() => ({ total: 0, broken: 0, missingAlt: 0 }));

        if (imageStats.broken === 0) {
            return {
                passed: true,
                details: `${imageStats.total} images found, 0 broken, ${imageStats.missingAlt} missing alt text`,
            };
        }
        return {
            passed: false,
            details: `${imageStats.broken} broken images out of ${imageStats.total}`,
            error: `${imageStats.broken} broken images`,
        };
    }

    // ═══════════════════════════════════════════
    // CONSOLE ERROR TESTS
    // ═══════════════════════════════════════════
    if (nameLower.includes('console') || nameLower.includes('error') || nameLower.includes('javascript')) {
        const errors = [];
        const consoleHandler = (msg) => {
            if (msg.type() === 'error') {
                errors.push(msg.text());
            }
        };
        page.on('console', consoleHandler);

        // Reload to capture fresh console errors
        await page.reload({ waitUntil: 'load', timeout: 15000 }).catch(() => {});
        await page.waitForTimeout(2000);

        page.off('console', consoleHandler);

        if (errors.length === 0) {
            return { passed: true, details: 'No console errors detected' };
        }
        return {
            passed: false,
            details: `${errors.length} console error(s): ${errors[0]?.substring(0, 80)}`,
            error: `${errors.length} errors found`,
        };
    }

    // ═══════════════════════════════════════════
    // RESPONSIVE / LAYOUT TESTS
    // ═══════════════════════════════════════════
    if (nameLower.includes('responsive') || nameLower.includes('mobile')) {
        // Check at mobile viewport
        await page.setViewportSize({ width: 375, height: 667 });
        await page.waitForTimeout(1000);

        const hasOverflow = await page.evaluate(() => {
            return document.body.scrollWidth > window.innerWidth;
        });

        // Reset viewport
        await page.setViewportSize({ width: 1920, height: 1080 });
        await page.waitForTimeout(500);

        if (!hasOverflow) {
            return { passed: true, details: 'Page adapts to mobile viewport without horizontal overflow' };
        }
        return { passed: false, details: 'Horizontal overflow detected at mobile viewport (375px)', error: 'Not responsive' };
    }

    // ═══════════════════════════════════════════
    // DEFAULT FALLBACK: Element visibility checks
    // ═══════════════════════════════════════════
    // Try to find elements matching the test name on page
    const searchText = testDesc.name
        .replace(/should|verify|check|test|that|the|is|are|has|have|be|visible|present|displayed|exist/gi, '')
        .trim();

    if (searchText.length > 2) {
        const found = await page.getByText(searchText, { exact: false }).first().isVisible().catch(() => false);
        if (found) {
            return { passed: true, details: `Element matching "${searchText}" is visible` };
        }
    }

    // If we can't determine what to test, check page is at least loaded
    const isLoaded = await page.evaluate(() => document.readyState).catch(() => 'unknown');
    return {
        passed: isLoaded === 'complete',
        details: `Page state: ${isLoaded} (generic check for: ${testDesc.name})`,
    };
}

module.exports = { executeGroqTests };
